### PR TITLE
Upgraded the styling and added Meta tags.

### LINKED ISSUE #12: Styling Issues
Hello:)
I saw your project and noticed some problems with style:

1. The border for the button looks weird.
2. The cursor is not pointer some people will think the button is disabled.
3. The Select menu lacks moder looks
4. In dark mode when you search the text is white so you can see it.
5. The output is not styled and hard to read
6. The theme switcher can be replaced with icons.

I would like to work on this

### LINKED ISSUE #13: Missing Meta Tags
Hello:)
I have noticed that the project lacks meta tags which can make the site more difficult to find online.
I would like to work on that.

### PR DESCRIPTION
**Pull request by Bashamega**
closes #12 
closes #13 
Hello:)
I have refactored the code and modified the styling

### CODE REVIEW

**Comment by BwnnyRxbbit** [comment]
Looks good, I have merged this! Thank you!

**Comment by Bashamega** [comment]
> Looks good, I have merged this! Thank you!

Your welcome

**Comment by BwnnyRxbbit** [comment]
Hi, can you explain to me how the meta tags work and what it does?

**Comment by Bashamega** [comment]
> Hi, can you explain to me how the meta tags work and what it does?

It is long to explain. But the conclusion is that it helps with SEO(search engine optimization).
You can read more about it here: https://www.w3schools.com/tags/tag_meta.asp

**Pull request merged**
