### PR TITLE
Airal font

### PR DESCRIPTION
**Pull request by mariocraft987**
Could be added

*arial

### CODE REVIEW

**Comment by BwnnyRxbbit** [comment]
I'm going to close this. Any changes to the styling should be made to the style.css file, not in HTML using the <style> tags.

**Comment by Rubiidev-IPad** [comment]
he put the font where it's supposed to be.

**Comment by BwnnyRxbbit** [comment]
> he put the font where it's supposed to be.

?

**Comment by mariocraft987** [comment]
She says `style.css`, not in the index.html itself

**Pull request closed without merging**
